services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    container_name: pr4-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./:/workspace

volumes:
  jenkins_home:
